name: raga_quiz
description: Carnatic Raga Quiz App
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/ragas.json
